import { Card } from '@preflop/ui';
import { Camera, Check, Code2, Coins, Cpu, Gem, LayoutPanelTop, Lock, Radio, Scale, Shuffle, Users, Wallet, Webhook, Wifi, type LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { ApplicationForm } from '../../components/site/ApplicationForm.tsx';
import { Eyebrow, SiteSection } from '../../components/site/SiteLayout.tsx';
import { StreamView } from '../../components/StreamView.tsx';

function Hero({ eyebrow, title, children, cards }: { eyebrow: string; title: string; children: ReactNode; cards: string[] }) {
  return (
    <SiteSection className="grid items-center gap-10 pb-10 pt-12 lg:grid-cols-[1.2fr_1fr] lg:pt-16">
      <div>
        <Eyebrow>{eyebrow}</Eyebrow>
        <h1 className="font-serif text-5xl leading-[1.05] sm:text-6xl">{title}</h1>
        <div className="mt-5 max-w-[620px] space-y-3 text-[17px] text-muted">{children}</div>
        <a href="#apply" className="mt-7 inline-flex h-12 items-center rounded-[14px] bg-accent px-6 font-semibold text-accent-ink hover:bg-accent-strong">Apply now</a>
      </div>
      <StreamView cards={cards} size="lg" className="hidden h-[300px] rounded-[18px] sm:block" badge={false} />
    </SiteSection>
  );
}

function Feature({ icon: I, title, children }: { icon: LucideIcon; title: string; children: ReactNode }) {
  return (
    <Card className="p-6">
      <I className="h-6 w-6 text-accent" strokeWidth={1.6} aria-hidden />
      <h3 className="mt-4 text-lg font-semibold">{title}</h3>
      <p className="mt-1.5 text-[15px] text-muted">{children}</p>
    </Card>
  );
}

function Grid({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) {
  return (
    <SiteSection className="py-12">
      <Eyebrow>{eyebrow}</Eyebrow>
      <h2 className="font-serif text-4xl leading-tight">{title}</h2>
      <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{children}</div>
    </SiteSection>
  );
}

function Checklist({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2.5">
      {items.map((x) => <li key={x} className="flex gap-3 text-[15px]"><Check className="mt-0.5 h-5 w-5 shrink-0 text-accent" aria-hidden /> <span>{x}</span></li>)}
    </ul>
  );
}

export function ForClubsPage() {
  return (
    <>
      <Hero eyebrow="For poker clubs" title="Every hand you deal becomes a market." cards={['Qs', 'Qd', '4c']}>
        <p>PreFlop players predict the flop at your tables while your games run as usual. You keep dealing; we handle pricing, payments, risk and settlement.</p>
        <p>Your tables earn a share of what they produce, measured every period from the hands you deal and the players you bring.</p>
      </Hero>

      <Grid eyebrow="Requirements" title="What a certified table needs">
        <Feature icon={Shuffle} title="PreFlop Trusted Shuffler">A laboratory-certified automatic shuffler owned by PreFlop, paired with the table. It signs every shuffle; a signal typed in by staff never counts.</Feature>
        <Feature icon={Camera} title="Approved cameras">The flop area must be clearly visible and hole cards must never be exposed. Camera angles are reviewed at certification.</Feature>
        <Feature icon={Radio} title="Live stream: dealer, shuffler, cards">Streaming is mandatory for betting to open. Viewers see the dealer, the shuffler, the cards and the flop, and never the players.</Feature>
        <Feature icon={Lock} title="Table Box security">A locked-down PreFlop device connects the cameras on an isolated network and signs hash-chained captures of every flop.</Feature>
        <Feature icon={Wifi} title="Stable internet with a backup line">At least 20 Mbps upload per table, low latency and an automatic 4G/5G or second-ISP failover. Monitored every second.</Feature>
        <Feature icon={Users} title="Trained dealers">Correct Start hand, the random cut chosen by PreFlop after betting closes, and flop entry. Sign-off for each dealer.</Feature>
      </Grid>

      <SiteSection className="grid gap-8 py-12 lg:grid-cols-2">
        <div>
          <Eyebrow>Revenue share</Eyebrow>
          <h2 className="font-serif text-4xl leading-tight">Paid for what your tables produce.</h2>
          <p className="mt-4 text-[17px] text-muted">Shares are not a fixed percentage. Each period your share is calculated from measured contribution, on a progressive ladder with no cliffs.</p>
        </div>
        <Card className="p-6">
          <Checklist items={[
            'Hands dealt: the flops your tables supply',
            'Active players you bring who play in the period',
            'Turnover generated by your traffic',
            'Fixed-odds shares are a percentage of gross gaming revenue; losing months carry forward',
            'Statements every period, straight from the ledger',
          ]} />
        </Card>
      </SiteSection>

      <SiteSection id="apply" className="scroll-mt-24 py-12">
        <ApplicationForm kind="club" title="Apply as a poker club" nameLabel="Club name" extra={[
          { key: 'city', label: 'City', required: true },
          { key: 'country', label: 'Country', required: true },
          { key: 'tables', label: 'Number of tables', type: 'number' },
          { key: 'website', label: 'Website', type: 'url', placeholder: 'https://' },
        ]} />
      </SiteSection>
    </>
  );
}

export function ForPartnersPage() {
  return (
    <>
      <Hero eyebrow="For betting companies" title="A live market your players have never seen." cards={['9h', 'Th', 'Jh']}>
        <p>Offer flop predictions from certified poker tables inside your product. Fast rounds, exact probabilities and a clean integration.</p>
      </Hero>
      <Grid eyebrow="Integration" title="Everything you need to go live">
        <Feature icon={Code2} title="Provider API">Signed REST API for rounds, prices and bets, with idempotency keys and stable problem types.</Feature>
        <Feature icon={LayoutPanelTop} title="Drop-in widget">Embed the table screen in an iframe with your player’s token. No website chrome, mobile-first, your brand colours.</Feature>
        <Feature icon={Wallet} title="Seamless wallet">Stakes and payouts call your wallet, so players keep one balance in your product.</Feature>
        <Feature icon={Webhook} title="Webhooks">Signed events for round lifecycle, settlement and voids, with retries and a delivery log.</Feature>
        <Feature icon={Scale} title="Exact pricing">Every price comes from all 22,100 flops with a published margin per channel.</Feature>
        <Feature icon={Cpu} title="Risk controls">Per-round exposure limits, a live integrity monitor and automatic voids when a table cannot be verified.</Feature>
      </Grid>
      <SiteSection id="apply" className="scroll-mt-24 py-12">
        <ApplicationForm kind="partner" title="Apply as a partner" nameLabel="Company name" extra={[
          { key: 'licences', label: 'Licensed jurisdictions', required: true, placeholder: 'e.g. MT, UK' },
          { key: 'website', label: 'Website', type: 'url', placeholder: 'https://' },
          { key: 'monthly_players', label: 'Monthly active players', type: 'number' },
          { key: 'integration', label: 'Preferred integration', placeholder: 'API, widget or both' },
        ]} />
      </SiteSection>
    </>
  );
}

export function ForOrganizersPage() {
  return (
    <>
      <Hero eyebrow="For organizers" title="Your room. Your community. Real tables." cards={['Ac', 'Ad', '7s']}>
        <p>Clubs, communities, streamers and betting brands can run their own PreFlop room on live tables, in virtual chips or diamonds.</p>
      </Hero>
      <Grid eyebrow="How rooms work" title="Clear rules, inside PreFlop’s guard rails">
        <Feature icon={Users} title="Rooms">Public or invite-only rooms on a table you choose. Players join with a code and play from a wallet that belongs to your room’s economy.</Feature>
        <Feature icon={Coins} title="Virtual chips">Buy chips from PreFlop and transfer them to your players. Set your margin or run a player pool with a rake, within global limits.</Feature>
        <Feature icon={Gem} title="Diamonds">Buy diamond packs with volume discounts. Every bet pays a fixed 1 ◆ fee to PreFlop and your rake to you.</Feature>
        <Feature icon={Lock} title="Collateral">When your room is the house, your collateral must cover the worst case of every open round before a bet is accepted.</Feature>
        <Feature icon={Scale} title="Dilution tracker">See diamonds bought, in circulation, sunk in fees, your rake and how many bets your remaining stock supports.</Feature>
        <Feature icon={Check} title="No cash value">Chips and diamonds never cash out on PreFlop. Check local rules for each territory before you launch.</Feature>
      </Grid>
      <SiteSection id="apply" className="scroll-mt-24 py-12">
        <ApplicationForm kind="organizer" title="Apply as an organizer" nameLabel="Organization or community" extra={[
          { key: 'community', label: 'Where is your community?', placeholder: 'Discord, club, stream…' },
          { key: 'expected_players', label: 'Expected players', type: 'number' },
          { key: 'currency', label: 'Chips or diamonds?', placeholder: 'Diamonds' },
          { key: 'country', label: 'Country' },
        ]} />
      </SiteSection>
    </>
  );
}
